Repository savushkin-r-d/ptusa_main, pull requests merged in 2021-12, with the labels that each got.

#333 Fix "F" device
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
Labels: bugfix

#334 Fix device "signal_column" processing
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev_lua.cpp
  PAC/common/tech_def.cpp
  PAC/common/tech_def.h
  PAC/common/toloa++/pkg/PAC_dev.hh
Labels: enhancement

#335 Fix compiler warnings
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_err.cpp
  PAC/common/bus_coupler_io.cpp
  PAC/common/mcaRec.cpp
  PAC/common/modbus_serv.cpp
  PAC/common/sys/debug.h
  PAC/linux/l_console.cpp
  PAC/linux/l_console.h
  PAC_control_projects/main_control_prg/main.cpp
  common/lua_manager.cpp
  sonar-project.properties
Labels: documentation

#337 Altivar FC connection lost error is local now, not critical
  PAC/IoT/iot_altivar.cpp
  PAC/common/PAC_err.cpp
  PAC/common/PAC_err.h
Labels: enhancement

#336 Add function to use signal column in shared way
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
Labels: enhancement

#341 Add code coverage calculation
  .github/workflows/cmake.yml
  CMakeLists.txt
  readme.md
Labels: documentation

#342 Fix debug IO-Link signal column
  PAC/common/PAC_dev.cpp
Labels: bugfix

#343 [cmake] Change version
  CMakeLists.txt
Labels: documentation
