Repository savushkin-r-d/ptusa_main, pull requests merged in 2021-03, with the labels that each got.

#210 Add test strategy
  docs/test/readme.md
  docs/test/readme_images/pic1.png
  docs/test/readme_images/pic2.png
  docs/test/readme_images/pic3.png
  docs/test/readme_images/pic4.png
Labels: documentation, enhancement

#212 Add Lua-available function
  PAC/common/PAC_dev_lua.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  PAC/common/toloa++/pkg/PAC_dev.hh
Labels: enhancement

#213 [cfg] Change version
  .gitignore
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc1.rc
Labels: documentation

#217 Add correct LUA path and add command line attributes for building
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.vcxproj
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc.vcxproj
Labels: enhancement

#218 Add path to .sln file for project
  readme.md
Labels: documentation

#223 Add error value to IO-Link devices
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
Labels: enhancement

#225 Add checking correct data in DI->DO action
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
Labels: enhancement

#220 Add howto build description
  demo_project/main.devices.lua
  demo_project/main.io.lua
  demo_project/main.modbus_srv.lua
  demo_project/main.objects.lua
  demo_project/main.plua
  demo_project/main.profibus.lua
  demo_project/main.restrictions.lua
  demo_project/sys/sys.devices.lua
  demo_project/sys/sys.io.lua
  demo_project/sys/sys.objects.lua
  demo_project/sys/sys.rm_PACs.lua
  readme.md
Labels: enhancement

#226 CIP UTF-8 adaptation
  PAC/common/PAC_dev_lua.cpp
  PAC/common/cip_stats.cpp
  PAC/common/cip_stats.h
  PAC/common/cip_tech_def.cpp
  PAC/common/cip_tech_def.h
  PAC/common/mcaRec.cpp
  PAC/common/mcaRec.h
  PAC/common/modbus_serv.cpp
  PAC/common/modbus_serv.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  common/util/utf2cp1251.cpp
  common/util/utf2cp1251.h
Labels: enhancement
