Repository savushkin-r-d/ptusa_main, pull requests merged in 2021-04, with the labels that each got.

#227 Fix parameters accessing
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
Labels: bugfix

#228 Add cmake-based library build
  CMakeLists.txt
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev_lua.cpp
  PAC/common/PAC_err.h
  PAC/common/mode_mngr.cpp
  PAC/common/param_ex.cpp
  PAC/common/prj_mngr.cpp
  PAC/common/tech_def.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  PAC_control_projects/main_control_prg/main.cpp
  common/PAC-driver/g_device.cpp
  common/PAC-driver/g_errors.cpp
  common/PAC-driver/g_errors.h
  common/lua_manager.cpp
Labels: enhancement

#229 Fix warnings
  CMakeLists.txt
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/bus_coupler_io.cpp
  PAC/common/bus_coupler_io.h
  PAC/common/cip_tech_def.cpp
  PAC/common/cip_tech_def.h
  PAC/common/log.h
  PAC/common/modbus_serv.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  PAC/common/rm_tech_def.h
  PAC/common/tech_def.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  PAC/win/w_rm_tech_def.cpp
  common/lua_manager.cpp
  common/win_util/SWMRG.cpp
Labels: enhancement

#230 [fix] Compilation issues
  PAC/common/PAC_dev.h
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc.vcxproj
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc.vcxproj.filters
  common/util/utf2cp1251.cpp
  lua_conf/luaconf.h
Labels: bugfix

#231 AS-I mixproof feedback bounce error time binded to open valve parameter time
  PAC/common/PAC_dev.h
Labels: enhancement

#232 Fix memory leaks
  .gitignore
  CMakeLists.txt
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PID.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  PAC/common/rm_manager.cpp
  PAC/common/tech_def.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.cpp
  common/PAC-driver/g_errors.cpp
  common/lua_manager.cpp
Labels: bugfix

#234 Remove unnecessary "lua_pcall"
  common/lua_manager.cpp
Labels: bugfix

#233 Work without "tcp_communicator" init
  common/lua_manager.cpp
Labels: enhancement

#235 Revert "Remove unnecessary "lua_pcall" (#234)"
  common/lua_manager.cpp
Labels: bugfix

#237 Fix library build
  CMakeLists.txt
Labels: bugfix

#238 Fix errors processing
  common/PAC-driver/g_errors.cpp
Labels: bugfix

#242 Fix encoding to UTF-8
  PAC/common/toloa++/pkg/PAC_dev.hh
Labels: bugfix, documentation

#241 Add main() parameters conversion to UTF-8 on windows
  .gitignore
  PAC/common/prj_mngr.cpp
  PAC_control_projects/main_control_prg/main.cpp
  common/lua_manager.cpp
Labels: enhancement

#240 Change PID-regulator
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/PID.cpp
  PAC/common/PID.h
  PAC/common/mode_mngr.cpp
  PAC/common/param_ex.h
  PAC/common/sys/dtime.h
Labels: enhancement

#245 Fix Linux build after changing PID-regulator
  PAC/common/PAC_dev.h
  PAC/common/PID.cpp
  PAC_control_projects/main_control_prg/main.cpp
Labels: bugfix

#243 Add message on the operation completion after the time of the last step
  PAC/common/i_tech_def.h
  PAC/common/mode_mngr.cpp
  PAC/common/tech_def.h
Labels: enhancement

#244 Rename R device to C
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
Labels: bugfix

#246 Add build with GitHub Actions
  .github/workflows/cmake.yml
  CMakeLists.txt
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  PAC/common/prj_mngr.cpp
  PAC/common/sys/s_types.h
  PAC_control_projects/main_control_prg/main.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/dllmain.cpp
  common/PAC-driver/g_errors.cpp
Labels: documentation, enhancement

#247 Add CTest-based simple test
  CMakeLists.txt
  CTestCustom.cmake
Labels: documentation, enhancement

#248 Fix discovered issues
  PAC/common/mcaRec.cpp
  PAC/common/modbus_serv.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/tech_def.cpp
  PAC/linux/l_console.cpp
  PAC/linux/l_mem.cpp
  PAC/linux/l_mem.h
  common/PAC-driver/g_errors.cpp
  common/util/utf2cp1251.cpp
Labels: bugfix

#250 Fix discovered issues
  PAC/common/bus_coupler_io.cpp
  PAC/common/tech_def.cpp
  PAC_control_projects/main_control_prg/main.cpp
Labels: bugfix

#251 Add CodeQL analysis action
  .github/workflows/codeql-analysis.yml
Labels: documentation, enhancement

#249 Add the build status badge
  readme.md
Labels: documentation, enhancement
