Repository savushkin-r-d/ptusa_main, pull requests merged in 2021-05, with the labels that each got.

#252 Modify log coloring
  PAC/linux/l_log.h
  PAC/win/w_console.h
  PAC/win/w_log.h
Labels: enhancement

#253 Better objects parameters processing
  PAC/common/param_ex.cpp
  PAC/common/param_ex.h
  PAC/common/tech_def.cpp
  PAC/common/tech_def.h
Labels: documentation, enhancement

#254 Replace pac_name_rus to pac_name_end in init
  common/lua_manager.cpp
Labels: bugfix

#257 Add writing function from Lua to syslog
  PAC/common/PAC_dev_lua.cpp
  PAC/common/log.cpp
  PAC/common/log.h
  PAC/common/toloa++/pkg/PAC_dev.hh
Labels: enhancement

#260 Fix PID controller
  PAC/common/PID.cpp
  PAC/common/mode_mngr.cpp
Labels: bugfix

#261 Fix PID controller
  PAC/common/PID.cpp
Labels: bugfix

#263 [cip] Close steam valve on signal "supply pump off"
  PAC/common/cip_tech_def.cpp
Labels: enhancement

#265 Add Axioline Smart Elements processing
  PAC/linux/l_bus_coupler_io.cpp
Labels: enhancement

#264 Add valve BURKERT 8694
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
Labels: enhancement

#266 Add Axioline Smart Elements processing
  PAC/common/bus_coupler_io.cpp
  PAC/linux/l_bus_coupler_io.cpp
Labels: bugfix
