Repository savushkin-r-d/ptusa_main, pull requests merged in 2022-09, with the labels that each got.

#481 Fix to step if devices in specific state action
  PAC/common/PAC_dev_lua.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/mode_mngr_tests.cpp
Labels: bugfix

#482 Fix "code smells"
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/bus_coupler_io.cpp
  PAC/common/cip_tech_def.cpp
  PAC/common/cip_tech_def.h
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  test/PAC_dev_tests.cpp
  test/mode_mngr_tests.cpp
Labels: bugfix

#483 [cmake] Change version
  CMakeLists.txt
Labels: documentation

#487 Add openhub.net project status
  readme.md
Labels: documentation

#486 Run Sonar analisis on pull_request_target
  .github/workflows/sonar_build.yml
Labels: documentation, safe to test

#489 Fix sonar_build action
  .github/workflows/sonar_build.yml
Labels: documentation

#490 Fix sonar_build action (pull request key)
  .github/workflows/sonar_build.yml
Labels: documentation

#491 Fix sonar_build action (pull_request.head.sha)
  .github/workflows/sonar_build.yml
Labels: documentation

#495 Fix action run condition
  .github/workflows/sonar_build.yml
Labels: documentation

#496 Fix sonar action run condition
  .github/workflows/sonar_build.yml
Labels: enhancement, bugfix

#494 Add processing Lua-function "get_run_step_after_pause"
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  PAC/common/tech_def.cpp
  PAC/common/tech_def.h
  common/lua_manager.cpp
  common/lua_manager.h
  test/tech_def_tests.cpp
  test/tech_def_tests.h
Labels: enhancement, safe to test

#502 Fix operation switching to the new state
  PAC/common/mode_mngr.cpp
  test/mode_mngr_tests.cpp
Labels: bugfix, safe to test

#485 Replace "Null" to "nullptr"
  PAC/common/PAC_dev.cpp
  PAC/common/bus_coupler_io.cpp
  PAC/common/cip_tech_def.cpp
  PAC/common/log.cpp
  PAC/common/mcaRec.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/param_ex.cpp
  PAC/common/param_ex.h
  PAC/common/prj_mngr.cpp
  PAC/common/tcp_client.cpp
  PAC/common/tcp_cmctr.cpp
  PAC/common/tech_def.cpp
  test/mcaRec_tests.cpp
Labels: enhancement, safe to test

#492 Add new device - threshold regulator
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/PID.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/PAC_dev_tests.cpp
Labels: enhancement, safe to test

#505 Fix CIP recipe objects destructor
  PAC/common/mcaRec.cpp
Labels: bugfix, safe to test
