Repository savushkin-r-d/ptusa_main, pull requests merged in 2022-04, with the labels that each got.

#394 Fix install yasm in GitHub actions
  .github/workflows/cmake.yml
Labels: enhancement

#387 Fix CAM control device
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/bus_coupler_io.cpp
  PAC/common/bus_coupler_io.h
  PAC/common/sys/base_mem.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  common/util/smart_ptr.h
  test/PAC_dev_tests.cpp
  test/main_test.cpp
  test/mock_params_manager.cpp
  test/mock_params_manager.h
Labels: bugfix

#393 FIx counter processing
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  test/PAC_dev_tests.cpp
Labels: bugfix

#390 Add debug functionality
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  test/PAC_dev_tests.cpp
Labels: enhancement

#402 Fix reconnect timeout calculation for I/O nodes
  PAC/common/bus_coupler_io.cpp
  PAC/common/bus_coupler_io.h
  PAC/linux/l_bus_coupler_io.cpp
Labels: bugfix

#405 Altivar FC enhancements
  PAC/IoT/iot_altivar.cpp
  PAC/IoT/iot_altivar.h
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_tests.cpp
Labels: enhancement

#400 Add function getting the number of operation steps
  PAC/common/PAC_dev_lua.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/PAC_dev_lua_tests.h
Labels: enhancement

#406 Update to the latest 2021 version
  CMakePresets.json
Labels: enhancement

#407 [cmake] Change version
  CMakeLists.txt
Labels: documentation

#398 Add counter with IO-Link interface
  CMakeLists.txt
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/bus_coupler_io.cpp
  PAC/common/bus_coupler_io.h
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  test/PAC_dev_tests.cpp
  test/mode_mngr_tests.cpp
Labels: enhancement

#401 Removed logic dependency from constant for additional debug messages
  CMakeLists.txt
  PAC/common/cip_tech_def.cpp
  common/lua_manager.h
  test/cip_tech_def_tests.cpp
  test/cip_tech_def_tests.h
Labels: bugfix

#408 Fix build presets name
  CMakePresets.json
Labels: documentation

#410 Fix bugs discovered by sonarcloud
  PAC/common/PAC_dev.h
Labels: bugfix

#409 Use number instead of numerical constant
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.hpp
Labels: bugfix

#416 [cmake] Use Visual Studio 2022 as Windows default
  CMakePresets.json
Labels: documentation

#415 Fix counter processing
  PAC/common/PAC_dev.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  test/PAC_dev_tests.cpp
  test/mode_mngr_tests.cpp
Labels: bugfix

#417 [cmake] Change version
  CMakeLists.txt
Labels: documentation
