Repository savushkin-r-d/ptusa_main, pull requests merged in 2022-02, with the labels that each got.

#356 Fixed issues after valgrind check
  PAC/IoT/iot_altivar.cpp
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/log.cpp
  PAC/common/log.h
  PAC/common/tcp_client.cpp
  PAC/linux/l_dtime.cpp
  PAC/linux/l_tcp_client.cpp
  PAC_control_projects/main_control_prg/main.cpp
Labels: bugfix

#357 Add new AXCF3152 target
  CMakePresets.json
Labels: documentation

#355 Optimize print I/O modules configuration
  CMakePresets.json
  PAC/common/bus_coupler_io.cpp
  test/bus_coupler_io_tests.cpp
  test/bus_coupler_io_tests.h
Labels: enhancement

#359 Remove communication with remote PACs
  PAC/IoT/IOT_dev_lua.cpp
  PAC/common/OPCUAServer.cpp
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/PAC_info.cpp
  PAC/common/PAC_info.h
  PAC/common/PID.h
  PAC/common/prj_mngr.cpp
  PAC/common/rm_manager.cpp
  PAC/common/rm_manager.h
  PAC/common/tech_def.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.cpp
  PAC/win/w_rm_tech_def.cpp
  PAC/win/w_rm_tech_def.h
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/src/PtusaMainPrg.cpp
  PAC_control_projects/main_control_prg/main.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.vcxproj
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.vcxproj.filters
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/Programs/MainPrg.cpp
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc.vcxproj
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc.vcxproj.filters
  PAC_control_projects/main_control_prg/nbproject/Makefile
  PAC_control_projects/main_control_prg/nbproject/configurations.xml
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/src/PtusaProgram.cpp
  common/PAC-driver/g_device.cpp
  common/PAC-driver/g_device.h
  common/PAC-driver/g_errors.h
  common/lua_manager.cpp
  common/lua_manager.h
  docs/test/readme.md
  test/PAC_info_tests.cpp
  test/PAC_info_tests.h
Labels: enhancement

#361 Add LGTM project badge
  readme.md
Labels: documentation

#360 Remove outdated projects
  PAC_control_projects/main_control_prg/bc++5/main_control_prg.ide
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/.project
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/CMakeLists.txt
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/plcnext.proj
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/src/PtusaMainCmpnt.cpp
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/src/PtusaMainCmpnt.hpp
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/src/PtusaMainPrg.hpp
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux-PLCnextEngineer/user_words
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-linux/.project
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-win/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/PLCnext-win/.project
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2014.10.3/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2014.10.3/.project
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2016.10.2/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2016.10.2/.project
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2016.2.1/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2016.2.1/.project
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2018.2.1/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2018.2.1/.project
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2019.5.1/.cproject
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2019.5.1/.gitignore
  PAC_control_projects/main_control_prg/eclipse/projects/WAGO-PFC-BSP-2019.5.1/.project
  PAC_control_projects/main_control_prg/eclipse_project/.cproject
  PAC_control_projects/main_control_prg/eclipse_project/.project
  PAC_control_projects/main_control_prg/eclipse_project/.settings/language.settings.xml
  PAC_control_projects/main_control_prg/eclipse_project/.settings/org.eclipse.cdt.codan.core.prefs
  PAC_control_projects/main_control_prg/eclipse_project/.settings/org.eclipse.core.resources.prefs
  PAC_control_projects/main_control_prg/eclipse_project/.settings/org.eclipse.core.runtime.prefs
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_Linux_main/.cproject
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_Linux_main/.project
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/.cproject
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/.project
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/MainCmp.cpp
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/MainCmp.hpp
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/MainCmpProgramProvider.cpp
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/MainCmpProgramProvider.hpp
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/Programs/MainPrg.hpp
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/PtusaLib.cpp
  PAC_control_projects/main_control_prg/main_control_prg_eclipse/PLCnext_PCworx_main/src/PtusaLib.hpp
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc.sln
  PAC_control_projects/main_control_prg/main_control_prg_vc/main_control_prg_vc1.rc
  PAC_control_projects/main_control_prg/main_control_prg_vc/resource1.h
  PAC_control_projects/main_control_prg/nbproject/project.xml
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa.sln
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/CMakeLists.txt
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/UndefClang.hpp
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/external/ADD_DEPENDENT_LIBRARIES_HERE.txt
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/plcnext.proj
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/ptusa.vcxproj
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/src/PtusaComponent.cpp
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/src/PtusaComponent.hpp
  PAC_control_projects/main_control_prg/visual_studio/ptusa/ptusa/src/PtusaProgram.hpp
  lua_conf/luaconf.h
Labels: enhancement, help wanted, documentation, no urgent

#363 Use the latest Visual Studio 2022
  .github/workflows/cmake.yml
Labels: enhancement, documentation

#365 Correct restrictions script number
  PAC/common/PAC_info.cpp
  test/PAC_info_tests.cpp
Labels: bugfix

#369 [cmake] Update version
  CMakeLists.txt
Labels: documentation
