Repository savushkin-r-d/ptusa_main, pull requests merged in 2022-12, with the labels that each got.

#526 Fix Definox sorio 1sv valve processing
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  test/PAC_dev_tests.cpp
Labels: bugfix, safe to test

#528 [cmake] Change project version
  CMakeLists.txt
Labels: documentation, bugfix, safe to test

#530 Fix spelling mistakes
  russian_readme/readme.md
Labels: documentation, safe to test

#531 [doc] Remove LGTM badge
  readme.md
Labels: documentation, safe to test

#534 [doc] Fix typos in readme file
  readme.md
  russian_readme/readme.md
Labels: documentation, safe to test
