Repository savushkin-r-d/ptusa_main, pull requests merged in 2022-07, with the labels that each got.

#452 Fix mingw compiler errors
  .github/workflows/cmake.yml
  CMakeLists.txt
  PAC/common/cip_tech_def.cpp
  PAC/common/param_ex.h
  PAC/linux/l_mem.cpp
  PAC/win/w_mem.cpp
Labels: bugfix

#450 Fix PID controller
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PID.cpp
  test/PAC_dev_tests.cpp
  test/PID_tests.cpp
  test/PID_tests.h
Labels: bugfix

#456 CIP station. Options for setting upper limit output for PIDs
  PAC/common/cip_tech_def.cpp
  PAC/common/cip_tech_def.h
  PAC/common/mcaRec.cpp
  PAC/common/mcaRec.h
  test/cip_tech_def_tests.cpp
Labels: enhancement

#446 Remove unnecessary sleeps
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.cpp
  PAC/linux/l_tcp_cmctr.cpp
  PAC_control_projects/main_control_prg/main.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.cpp
  test/l_tcp_cmctr_tests.cpp
  test/l_tcp_cmctr_tests.h
Labels: enhancement

#459 Add Mingw64 preset
  CMakePresets.json
Labels: enhancement

#460 [cmake] Change version
  CMakeLists.txt
Labels: enhancement

#468 Fix processing sockets
  PAC/linux/l_tcp_cmctr.cpp
  PAC/win/w_tcp_cmctr.cpp
Labels: bugfix

#469 [cmake] Change version
  CMakeLists.txt
Labels: enhancement, documentation

#472 Revert changes from #468 and #446
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.cpp
  PAC/linux/l_tcp_cmctr.cpp
  PAC/win/w_tcp_cmctr.cpp
  PAC_control_projects/main_control_prg/main.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.cpp
  test/l_tcp_cmctr_tests.cpp
  test/l_tcp_cmctr_tests.h
Labels: bugfix

#473 [cmake] Update version
  CMakeLists.txt
Labels: enhancement, documentation
