Repository savushkin-r-d/ptusa_main, pull requests merged in 2022-11, with the labels that each got.

#512 Refactor "jump_if_action" action
  PAC/common/PAC_dev_lua.cpp
  PAC/common/mode_mngr.cpp
  PAC/common/mode_mngr.h
  PAC/common/tech_def.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/mode_mngr_tests.cpp
  test/tech_def_tests.cpp
Labels: enhancement, bugfix, safe to test

#514 [cmake] Change version
  CMakeLists.txt
Labels: documentation, safe to test

#518 Add general system architecture description
  readme.md
  readme_images/system_architecture_en.png
  readme_images/system_architecture_ru.png
  russian_readme/readme.md
Labels: documentation, safe to test

#521 Fix DRAKON diagram style
  docs/drakon_diagram/images/action.svg
  docs/drakon_diagram/images/action_en.svg
  docs/drakon_diagram/images/control_program.svg
  docs/drakon_diagram/images/control_program_en.svg
  docs/drakon_diagram/images/execution_technological_process.svg
  docs/drakon_diagram/images/execution_technological_process_en.svg
  docs/drakon_diagram/images/operation.svg
  docs/drakon_diagram/images/operation_en.svg
  docs/drakon_diagram/images/step.svg
  docs/drakon_diagram/images/step_en.svg
  docs/drakon_diagram/images/steps.svg
  docs/drakon_diagram/images/steps_en.svg
  docs/drakon_diagram/images/unit_procedure.svg
  docs/drakon_diagram/images/unit_procedure_en.svg
  readme.md
  russian_readme/readme.md
Labels: documentation, safe to test

#515 [cip] Add errors for temperature and conductivity sensors
  PAC/common/cip_tech_def.cpp
  PAC/common/cip_tech_def.h
  test/cip_tech_def_tests.cpp
Labels: enhancement, safe to test
