Repository savushkin-r-d/ptusa_main, pull requests merged in 2023-08, with the labels that each got.

#598 Fix inheritance "valve_DO2"
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  test/PAC_dev_tests.cpp
Labels: safe to test

#599 Add property "tag" to class "step"
  PAC/common/PAC_dev_lua.cpp
  PAC/common/operation_mngr.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/operation_mngr_tests.cpp
Labels: enhancement, safe to test, good first issue

#600 [config][github actions] Update "actions/setup-java" to v3
  .github/workflows/sonar_build.yml
Labels: documentation, safe to test

#601 [config][cmake] Change project version
  CMakeLists.txt
Labels: documentation, safe to test

#603 [config][sonar] Update sonar scanner version to 5.0.1.3006
  .github/workflows/sonar_build.yml
Labels: documentation, safe to test, good first issue

#604 [config][git] Ignore PAC memory file
  .gitignore
Labels: documentation, safe to test

#602 [doc] Add installation toolchain description
  readme.md
  russian_readme/readme.md
Labels: safe to test

#613 [config][github actions] Add "merge_group" event processing
  .github/workflows/cmake.yml
Labels: documentation, safe to test

#615 [config][github actions] Add "merge_group" event processing
  .github/workflows/codeql-analysis.yml
  .github/workflows/sonar_build.yml
Labels: documentation, safe to test

#609 Save operation time and main step time as "tech_object" tags
  PAC/common/operation_mngr.cpp
  PAC/common/operation_mngr.h
  PAC/common/param_ex.h
  PAC/common/tech_def.cpp
  PAC/common/tech_def.h
  test/tech_def_tests.cpp
Labels: enhancement, safe to test

#611 Fix controller self-assigment bug
  PAC/common/PID.cpp
  PAC/common/PID.h
  test/PID_tests.cpp
Labels: bugfix, safe to test

#614 Rename "operation number" variable
  PAC/common/operation_mngr.cpp
  PAC/common/operation_mngr.h
Labels: safe to test

#618 Fix threshold regulator parameters name
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  test/PAC_dev_tests.cpp
Labels: bugfix, safe to test
