Repository savushkin-r-d/ptusa_main, pull requests merged in 2023-02, with the labels that each got.

#546 [github actions] Fix benchmark processing
  .github/workflows/cmake.yml
Labels: documentation, bugfix, safe to test

#547 [github actions] Revert benchmark build target
  .github/workflows/cmake.yml
Labels: documentation, bugfix, safe to test

#548 [github actions] Refactor benchmark parameters
  .github/workflows/cmake.yml
Labels: enhancement, documentation, safe to test

#545 [doc] Add description of libraries
  readme.md
  russian_readme/readme.md
Labels: enhancement, documentation, safe to test, good first issue

#549 [cmake] Fix cmake configuration
  .github/workflows/cmake.yml
  CMakeLists.txt
Labels: bugfix, safe to test

#551 Update GitHub action "CodeQL" to version "v2"
  .github/workflows/codeql-analysis.yml
Labels: enhancement, safe to test

#556 [config][cmake] Change version
  CMakeLists.txt
Labels: documentation, safe to test

#555 Add new control device "V_IOL_TERMINAL_MIXPROOF_DO3"
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  test/PAC_dev_tests.cpp
Labels: enhancement, safe to test, good first issue
