Repository savushkin-r-d/ptusa_main, pull requests merged in 2023-04, with the labels that each got.

#577 [config][github actions] Update build workflow
  .github/workflows/cmake.yml
Labels: bugfix, safe to test

#580 [config][cmake] Change project version
  CMakeLists.txt
Labels: documentation, safe to test

#579 [doc] Edit system architecture scheme
  readme.md
  readme_images/system_architecture_2_en.png
  readme_images/system_architecture_2_ru.png
  readme_images/system_architecture_en.png
  readme_images/system_architecture_ru.png
  russian_readme/readme.md
Labels: documentation, safe to test

#581 [config][cmake] Change project version
  CMakeLists.txt
Labels: documentation, safe to test

#583 Add functions to control verbosity
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.cpp
  test/dll/main_control_dll_tests.cpp
Labels: enhancement, safe to test

#553 Add simulation for analog control modules
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/analog_emulator.cpp
  PAC/common/analog_emulator.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/PAC_dev_tests.cpp
  test/analog_emulator_tests.cpp
  test/analog_emulator_tests.h
Labels: enhancement, safe to test, good first issue
