Repository savushkin-r-d/ptusa_main, pull requests merged in 2024-09, with the labels that each got.

#734 [config][dependabot] Add gits submodules processing
  .github/dependabot.yml
Labels: enhancement, documentation, safe to test, dependencies

#742 Fix error: ‘put_time’ is not a member of ‘std’
  test/prj_mngr_tests.cpp
Labels: bugfix, safe to test

#718 Добавил менеджер параметрических рецептов
  PAC/common/PAC_dev_lua.cpp
  PAC/common/bus_coupler_io.cpp
  PAC/common/cip_tech_def.cpp
  PAC/common/operation_mngr.cpp
  PAC/common/params_recipe_manager.cpp
  PAC/common/params_recipe_manager.h
  PAC/common/prj_mngr.cpp
  PAC/common/tech_def.cpp
  PAC/common/tech_def.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  common/PAC-driver/g_device.cpp
  test/params_recipe_manager_tests.cpp
  test/params_recipe_manager_tests.h
  test/tech_def_tests.cpp
Labels: enhancement, safe to test

#745 [config][cmake] Change project version
  CMakeLists.txt
Labels: documentation, safe to test

#746 [fix] Move usage of fmt::format_to_n from *.h to *.cpp
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
Labels: bugfix, safe to test

#748 Fix sockets processing
  PAC/linux/l_tcp_cmctr.cpp
  PAC/win/w_tcp_cmctr.cpp
Labels: bugfix, safe to test, urgent

#751 [fix] Disable exchange with altivar motors
  PAC_control_projects/main_control_prg/main.cpp
Labels: bugfix, safe to test, urgent

#752 [config][cmake] Change project version
  CMakeLists.txt
Labels: documentation, safe to test

#754 [tests] Fix ParamsRecipeStorage test
  test/params_recipe_manager_tests.cpp
Labels: bugfix, safe to test

#757 Add I/O modules range checking
  PAC/common/PAC_dev.h
  PAC/common/bus_coupler_io.cpp
  PAC/common/bus_coupler_io.h
  test/PAC_dev_tests.cpp
Labels: enhancement, safe to test

#749 Fix emulator mode
  CMakeLists.txt
  PAC/IoT/IOT_dev_lua.cpp
  PAC/common/OPCUAServer.cpp
  PAC/common/OPCUAServer.h
  PAC/common/PAC_dev.cpp
  PAC/common/PAC_dev.h
  PAC/common/PAC_dev_lua.cpp
  PAC/common/PAC_info.cpp
  PAC/common/PAC_info.h
  PAC/common/PID.h
  PAC/common/cip_tech_def.h
  PAC/common/device/analog_emulator.cpp
  PAC/common/device/analog_emulator.h
  PAC/common/device/base.cpp
  PAC/common/device/base.h
  PAC/common/device/device.cpp
  PAC/common/device/device.h
  PAC/common/device/manager.cpp
  PAC/common/device/manager.h
  PAC/common/device/valve.cpp
  PAC/common/device/valve.h
  PAC/common/mcaRec.cpp
  PAC/common/operation_mngr.h
  PAC/common/param_ex.cpp
  PAC/common/params_recipe_manager.cpp
  PAC/common/prj_mngr.cpp
  PAC/common/tech_def.cpp
  PAC/common/tech_def.h
  PAC/common/toloa++/pkg/IOT_dev.hh
  PAC/common/toloa++/pkg/PAC_dev.hh
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.cpp
  PAC_control_projects/main_control_prg/main.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.cpp
  common/PAC-driver/g_device.cpp
  common/PAC-driver/g_device.h
  common/PAC-driver/g_errors.cpp
  common/PAC-driver/g_errors.h
  common/lua_manager.cpp
  test/OPCUAServer_tests.cpp
  test/PAC_dev_lua_tests.cpp
  test/PAC_dev_lua_tests.h
  test/PAC_dev_tests.h
  test/analog_emulator_tests.h
  test/cip_tech_def_tests.h
  test/device/PAC_dev_tests.cpp
  test/device/PAC_dev_tests.h
  test/g_errors_tests.cpp
  test/g_errors_tests.h
  test/operation_mngr_tests.cpp
Labels: bugfix, safe to test

#758 [config][cmake] Change version
  CMakeLists.txt
Labels: documentation, safe to test

#755 Add device GEA TVIS A15
  PAC/common/device/manager.cpp
  PAC/common/device/valve.cpp
  PAC/common/device/valve.h
  test/device/PAC_dev_tests.cpp
Labels: enhancement, safe to test

#759 [config][github actions] Change sonar project version
  sonar-project.properties
Labels: dependencies
