Repository savushkin-r-d/ptusa_main, pull requests merged in 2024-10, with the labels that each got.

#761 Fix library for PLCNext
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.cpp
Labels: enhancement, bugfix, safe to test

#766 [config][cmake] Change version
  CMakeLists.txt
Labels: bugfix, safe to test

#767 Fix library for PLCNext
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.cpp
Labels: bugfix

#768 Refactor GEA IO-Link valve
  PAC/common/device/valve.cpp
  PAC/common/device/valve.h
  test/device/PAC_dev_tests.cpp
Labels: bugfix, safe to test

#769 [config][cmake] Change version
  CMakeLists.txt
Labels: documentation

#778 [tests] Speed up tests
  test/device/PAC_dev_tests.cpp
  test/includes.h
  test/main_test.cpp
  test/operation_mngr_tests.cpp
  test/tech_def_tests.cpp
Labels: enhancement, safe to test

#776 [cmake][config] Use C++17 standard
  CMakeLists.txt
Labels: enhancement, safe to test

#780 [config][github actions] Add codecov configuration
  .github/codecov.yml
Labels: safe to test

#782 Fix of typo
  PAC/common/uni_bus_coupler_io.cpp
Labels: bugfix, safe to test

#781 [config][github actions] Remove tests from code coverage for Sonar
  sonar-project.properties
Labels: enhancement, safe to test

#784 [tests] Fix code issues detected by Sonar
  test/device/PAC_dev_tests.cpp
Labels: enhancement, safe to test

#779 [tests] Добавление тестов для менеджера рецептов
  common/PAC-driver/g_device.cpp
  test/cip_tech_def_tests.cpp
  test/device/PAC_dev_tests.cpp
  test/g_device_tests.cpp
  test/includes.h
  test/main_test.cpp
  test/operation_mngr_tests.cpp
  test/params_recipe_manager_tests.cpp
  test/tech_def_tests.cpp
Labels: enhancement, safe to test

#787 [doc] Fix typos
  docs/russian_readme/readme.md
Labels: documentation, bugfix, safe to test

#785 Add daily fields to the counter
  PAC/common/PAC_dev_lua.cpp
  PAC/common/device/base.cpp
  PAC/common/device/base.h
  PAC/common/device/device.cpp
  PAC/common/device/device.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/device/PAC_dev_tests.cpp
Labels: enhancement, safe to test
