Repository savushkin-r-d/ptusa_main, pull requests merged in 2024-12, with the labels that each got.

#808 Fix stub functionality
  PAC/common/PAC_dev_lua.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/device/PAC_dev_tests.cpp
Labels: bugfix, safe to test

#811 Change the maximum number of sockets
  PAC/common/tcp_cmctr.h
Labels: enhancement, safe to test

#813 Fix work with /dev/random
  PAC/common/device/analog_emulator.cpp
  PAC/common/device/analog_emulator.h
Labels: bugfix, safe to test

#814 [config][cmake] Change version to 2024.12.12.1
  CMakeLists.txt
Labels: enhancement, safe to test

#817 Fix digital valves
  PAC/common/device/valve.cpp
  PAC/common/device/valve.h
  test/device/PAC_dev_tests.cpp
Labels: bugfix, safe to test, urgent

#818 [config][cmake] Change version to 2024.12.12.2
  CMakeLists.txt
Labels: enhancement, documentation, safe to test

#820 Fix general DO device
  PAC/common/device/base.cpp
  PAC/common/device/base.h
  PAC/common/device/valve.cpp
  PAC/common/device/valve.h
  test/device/PAC_dev_tests.cpp
Labels: bugfix, safe to test, urgent

#822 [config][cmake] Change version to 2024.12.12.3
  CMakeLists.txt
Labels: enhancement, documentation, safe to test

#816 [cip] Fix string buffer size
  PAC/common/mcaRec.cpp
Labels: bugfix, safe to test

#825 [cip] Fix unused variables
  PAC/common/cip_tech_def.cpp
  test/cip_tech_def_tests.cpp
Labels: bugfix, safe to test

#783 Improvement of maintainability
  PAC/IoT/iot_altivar.cpp
  PAC/common/PAC_dev_lua.cpp
  PAC/common/PID.cpp
  PAC/common/bus_coupler_io.cpp
  PAC/common/bus_coupler_io.h
  PAC/common/cip_tech_def.cpp
  PAC/common/device/base.cpp
  PAC/common/device/device.cpp
  PAC/common/device/manager.cpp
  PAC/common/device/valve.cpp
  PAC/common/device/valve.h
  PAC/common/modbus_client.cpp
  PAC/common/modbus_client.h
  PAC/common/modbus_serv.cpp
  PAC/common/operation_mngr.cpp
  PAC/common/params_recipe_manager.cpp
  PAC/common/params_recipe_manager.h
  PAC/common/tech_def.cpp
  PAC/common/toloa++/pkg/PAC_dev.hh
  PAC/linux/l_tcp_client.cpp
  PAC/linux/l_tcp_cmctr.cpp
  PAC/win/w_tcp_client.cpp
  PAC/win/w_tcp_cmctr.cpp
  PAC_control_projects/main_control_prg/main_control_dll_vc/main_control_dll_vc.cpp
  common/PAC-driver/g_errors.cpp
  common/lua_manager.cpp
  common/lua_manager.h
  test/PID_tests.cpp
  test/cip_tech_def_tests.cpp
  test/device/PAC_dev_tests.cpp
  test/lua_manager_tests.cpp
  test/modbus_client_tests.cpp
  test/modbus_client_tests.h
  test/modbus_serv_tests.cpp
  test/modbus_serv_tests.h
  test/tcp_client_test.cpp
  test/tcp_cmctr_tests.cpp
  test/tech_def_tests.cpp
Labels: enhancement, help wanted, safe to test
