Repository savushkin-r-d/ptusa_main, pull requests merged in 2024-02, with the labels that each got.

#648 [config][github-actions] Update codecov action to v4
  .github/workflows/cmake.yml
Labels: enhancement, documentation, safe to test

#653 [test] Fix OPC UA
  test/PAC_info_tests.cpp
Labels: bugfix, safe to test

#652 [config][github actions] Update actions to v4 version
  .github/workflows/cmake.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/sonar_build.yml
Labels: enhancement, documentation, safe to test

#658 Fix IO-Link concentration sensor
  PAC/common/PAC_dev.cpp
Labels: bugfix, safe to test

#659 [config][cmake] Change version
  CMakeLists.txt
Labels: enhancement, documentation, safe to test

#656 Modernize to_next_step()
  PAC/common/operation_mngr.cpp
  test/operation_mngr_tests.cpp
Labels: enhancement, safe to test
