Repository savushkin-r-d/ptusa_main, pull requests merged in 2025-03, with the labels that each got.

#867 Fix max step duration message
  PAC/common/operation_mngr.cpp
  PAC/common/tech_def.cpp
  test/tech_def_tests.cpp
Labels: bugfix, safe to test

#860 Отсечение времени одной итерации главного цикла
  CMakeLists.txt
  PAC/common/PAC_info.cpp
  PAC/common/PAC_info.h
  PAC/common/device/device.cpp
  PAC/common/device/valve.cpp
  PAC/common/device/valve.h
  PAC/common/tcp_cmctr.cpp
  PAC/common/tcp_cmctr.h
  PAC_control_projects/main_control_prg/main.cpp
  PAC_control_projects/main_control_prg/main_cycle.cpp
  PAC_control_projects/main_control_prg/main_cycle.h
  common/PAC-driver/g_device.cpp
  common/PAC-driver/g_device.h
  test/OPCUAServer_tests.cpp
  test/PAC_dev_lua_tests.cpp
  test/PAC_info_tests.cpp
  test/PID_tests.cpp
  test/device/PAC_dev_tests.cpp
  test/g_device_tests.cpp
  test/g_errors_tests.cpp
  test/main_cycle_test.cpp
  test/main_cycle_test.h
  test/tcp_cmctr_tests.cpp
Labels: enhancement, safe to test

#858 Исправление ошибки со счётчиком
  PAC/common/device/base.h
  PAC/common/device/device.cpp
  PAC/common/device/device.h
  common/PAC-driver/g_errors.cpp
  test/device/PAC_dev_tests.cpp
  test/g_device_tests.cpp
Labels: bugfix, safe to test

#869 Добавлен метод для виртуального устройства-заглушки STUB
  PAC/common/PAC_dev_lua.cpp
  PAC/common/device/device.cpp
  PAC/common/device/device.h
  PAC/common/toloa++/pkg/PAC_dev.hh
  test/PAC_dev_lua_tests.cpp
  test/device/PAC_dev_tests.cpp
Labels: enhancement, safe to test, good first issue

#872 [config][cmake] Change version to 2025.03.12
  CMakeLists.txt
Labels: enhancement, safe to test

#876 [config][cmake] Change version to 2025.03.12.1
  CMakeLists.txt
Labels: enhancement, safe to test

#875 Fix over range error for I/O modules 750-466, 750-496
  PAC/common/bus_coupler_io.cpp
  PAC/common/device/base.h
  PAC/common/device/device.cpp
  test/device/PAC_dev_tests.cpp
Labels: bugfix, safe to test

#879 Fix cycle time calculation for PLCnext
  PAC/linux/PAC_PLCnext/PtusaPLCnextEngineer/PtusaMainPrg.cpp
Labels: bugfix, safe to test

#880 [config][cmake] Change version to 2025.03.12.2
  CMakeLists.txt
Labels: enhancement, documentation, safe to test

#878 Fix QT control module error message
  PAC/common/bus_coupler_io.h
  PAC/common/device/base.cpp
  PAC/common/device/base.h
  PAC/common/device/device.cpp
  PAC/common/device/device.h
  test/device/PAC_dev_tests.cpp
Labels: bugfix, safe to test

#883 Fix debug message for the control module G
  PAC/common/device/device.cpp
Labels: bugfix, safe to test

#885 [config][cmake] Fix PLCnext build
  CMakeLists.txt
Labels: bugfix, safe to test

#886 [config][cmake] Change version to 2025.03.12.3
  CMakeLists.txt
Labels: documentation, safe to test

#887 [config] Add total build time print
  misc/bi_all.sh
Labels: enhancement, documentation, safe to test

#889 Fix "FQT" control device
  PAC/common/device/device.cpp
  test/device/PAC_dev_tests.cpp
Labels: bugfix, safe to test
