Repository savushkin-r-d/ptusa_main, pull requests merged in 2025-01, with the labels that each got.

#827 [cip] Fix load cip recipes
  PAC/common/mcaRec.cpp
Labels: bugfix, safe to test

#836 [config][github actions] Fix code coverage calculation
  .github/workflows/cmake.yml
Labels: bugfix, safe to test

#837 [config][github actions] Fix code coverage calculation
  .github/workflows/cmake.yml
Labels: bugfix

#838 [config][github actions] Fix SonarQube build
  .github/workflows/sonar_build.yml
  sonar-project.properties
Labels: bugfix, safe to test

#842 [config][github actions] Add valgrind installation
  .github/workflows/cmake.yml
Labels: safe to test, dependencies

#835 Fix memory leaks in the OPC UA server
  PAC/common/OPCUAServer.cpp
  PAC/common/device/manager.cpp
  PAC/linux/PAC_PC/profibus_slave_PC.cpp
  PAC/linux/PAC_PC/profibus_slave_PC.h
  common/lua_manager.cpp
  common/lua_manager.h
  test/OPCUAServer_tests.cpp
  test/dll/main_control_dll_tests.cpp
  test/includes.h
  test/lua_manager_dependencies.cpp
  test/lua_manager_dependencies.h
  test/lua_manager_tests.cpp
  test/main_test.cpp
Labels: bugfix, safe to test

#844 Исправление ошибки в документации
  docs/russian_readme/readme.md
  readme.md
Labels: documentation
