Repository savushkin-r-d/ptusa_main, pull requests merged in 2025-09, with the labels that each got.

#1013 [Fix] Correct max out value for watchdog
  PAC/common/device/life_device.h
Labels: bugfix, safe to test

#1041 [config][github actions] Fixes CMake build
  .github/workflows/cmake.yml
Labels: bugfix

#1044 [config][github actions] Refactor analysis on pull requests
  .github/workflows/sonar_build.yml
Labels: enhancement, safe to test, github_actions

#1048 Fixes initial valve state after converter binding
  PAC/common/device/valve.cpp
  test/device/PAC_dev_tests.cpp
Labels: bugfix
